packages:
  - !include config.yaml
  - !include data/fonts.yaml
  - !include data/images.yaml
  - !include data/mappings.yaml
  - !include data/text_sensors.yaml
  - !include data/times.yaml

esphome:
  name: hosttest
  friendly_name: HOSTTEST

host:

api:

logger:
  level: DEBUG

display:
  - platform: sdl
    show_test_card: false
    dimensions:
      width: 1280
      height: 800

touchscreen:
  - platform: sdl
    on_touch:
      then:
        - lvgl.page.next:
            animation: OUT_LEFT
            time: 300ms

lvgl:
  pages:
    - id: home_page
      widgets: !include
        file: pages/home.yaml
    - id: daily_page
      widgets: !include
        file: pages/daily.yaml
    - id: hourly_page
      widgets: !include
        file: pages/hourly.yaml

