# Guition-ESP32-P4-JC8012P4A1 Smart Screen
# Hardware configuration file
# Original file from: https://github.com/agillis/esphome-modular-lvgl-buttons/blob/29410088b8520b870e00e996c278d1a822031842/modules/hardware/guition-esp32-p4-jc8012p4a1.yaml
# with the help of: https://community.home-assistant.io/t/jc8012p4a1-guition-esp32-p4-esp32-c6/939971
# and kvj: https://github.com/kvj/esphome

packages:
  - !include data/fonts.yaml
  - !include data/images.yaml
  - !include data/mappings.yaml
  - !include data/text_sensors.yaml
  - !include data/times.yaml

substitutions:
  font: "fonts/OpenSans-Medium.ttf"

esphome:
  name: "weatherdisplay"
  friendly_name: "WeatherDisplay"

external_components:
  - source: github://kvj/esphome@jd9365_gsl3680
    refresh: 0s
    components: [gsl3680, jd9365]

esp32:
  board: esp32-p4-evboard
  cpu_frequency: 360MHz
  flash_size: 16MB
  framework:
    type: esp-idf

esp_ldo:
  - channel: 3
    voltage: 2.5V

psram:
  speed: 200MHz

i2c:
  - id: i2c_bus
    sda: GPIO7
    scl: GPIO8
    scan: true
    frequency: 400kHz

i2c_device:
  - id: i2cdev1
    address: 0x18
  - id: i2cdev2
    address: 0x32
  - id: i2cdev3
    address: 0x36
  - id: i2cdev4
    address: 0x40

output:
    platform: ledc
    pin: GPIO23
    id: backlight

light:
  - platform: monochromatic
    id: lcd_backlight
    name: "backlight"
    output: backlight
    restore_mode: ALWAYS_ON

script:
  - id: backlight_watchdog
    mode: restart
    then:
      - light.turn_on: lcd_backlight
      - delay: 2min
      - light.turn_off: lcd_backlight

touchscreen:
  - platform: gsl3680
    id: my_touch
    reset_pin: GPIO22
    interrupt_pin: GPIO21
    transform:
      swap_xy: true
      mirror_y: false
    on_touch:
      then:
        - script.execute: backlight_watchdog
        - if:
            condition:
              light.is_on: lcd_backlight
            then:
              - lvgl.page.next:
            else:
              - light.turn_on: lcd_backlight

display:
  - platform: jd9365
    reset_pin: GPIO27
    auto_clear_enabled: false
    show_test_card: false
    rotation: 90
    id: my_display

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_hosted:
  variant: ESP32C6
  reset_pin: 54
  cmd_pin: 19
  clk_pin: 18
  d0_pin: 14
  d1_pin: 15
  d2_pin: 16
  d3_pin: 17
  active_high: true

api:

json:

# this is required for succesful compilation.
# It doesn't need to be 'valid', it just needs to be there
switch:
  - platform: homeassistant
    id: any_id
    entity_id: switch.any_id
    internal: true

lvgl:
  touchscreens:
    - touchscreen_id: my_touch
  byte_order: little_endian
  pages:
    - id: home_page
      widgets: !include
        file: pages/home.yaml
    - id: daily_page
      widgets: !include
        file: pages/daily.yaml
    - id: hourly_page
      widgets: !include
        file: pages/hourly.yaml

logger:
  hardware_uart: USB_SERIAL_JTAG
  level: DEBUG
  logs:
    lvgl: DEBUG
    display: DEBUG
    app: DEBUG
