# Guition-ESP32-P4-JC8012P4A1 Smart Screen
# Hardware configuration file
# Original file from: https://github.com/agillis/esphome-modular-lvgl-buttons/blob/29410088b8520b870e00e996c278d1a822031842/modules/hardware/guition-esp32-p4-jc8012p4a1.yaml

packages:
  - !include config.yaml
  - !include data/fonts.yaml
  - !include data/images.yaml
  - !include data/mappings.yaml
  - !include data/text_sensors.yaml
  - !include data/times.yaml

external_components:
  - source: github://willumpie82/esphome@dev
    components: [mipi_dsi]
  - source: github://kvj/esphome@jd9365_gsl3680
    components: [gsl3680]

esphome:
  min_version: 2025.10.0
  name: "weatherdisplay"
  friendly_name: "WeatherDisplay"

esp32:
  board: esp32-p4-evboard
  cpu_frequency: 400MHz
  flash_size: 16MB
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: yes

esp_ldo:
  - channel: 3
    voltage: 2.5V

psram:
  speed: 200MHz

preferences:
  flash_write_interval: 5min

esp32_hosted:
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17
  active_high: true

output:
  - platform: ledc
    pin: GPIO23
    id: gpio_backlight_pwm
    frequency: 100Hz
    min_power: 0.03
    zero_means_zero: true

light:
  - platform: monochromatic
    output: gpio_backlight_pwm
    name: Display Backlight
    icon: mdi:lightbulb-on
    id: display_backlight
    restore_mode: ALWAYS_ON

i2c:
  - id: bus_a
    sda: GPIO7
    scl: GPIO8
    scan: true
    frequency: 400kHz

i2c_device:
  - id: i2cdev1
    address: 0x18
  - id: i2cdev2
    address: 0x32
  - id: i2cdev3
    address: 0x36
  - id: i2cdev4
    address: 0x40

touchscreen:
  - platform: gsl3680
    id: my_touchscreen
    reset_pin: GPIO22
    interrupt_pin: GPIO21
    transform:
      swap_xy: false
      mirror_x: false
      mirror_y: true
    on_touch:
      then:
        - lvgl.page.next:
            animation: OUT_LEFT
            time: 300ms

display:
  - platform: mipi_dsi
    model: JC8012P4A1
    id: my_display
    update_interval: never
    reset_pin: GPIO27
    rotation: 180
    auto_clear_enabled: false
    color_order: RGB
    dimensions:
      width: 800
      height: 1280

lvgl:
  byte_order: little_endian
  pages:
    - id: home_page
      widgets: !include
        file: pages/home.yaml
    - id: daily_page
      widgets: !include
        file: pages/daily.yaml
    - id: hourly_page
      widgets: !include
        file: pages/hourly.yaml

api:

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
